export interface PokemonType {
  name: string;
  color: string;
  damage: Multiplier;
}

export interface Multiplier {
  none: Set<PokemonType>,
  half: Set<PokemonType>,
  double: Set<PokemonType>
}

function emptyMult(): Multiplier {
  return { none: new Set(), half: new Set(), double: new Set() }
}

export function getTypeMultiplierRaw(attack: PokemonType, defense: PokemonType, typeType: boolean = false): number {
  if (attack == TYPE_RIGHT && defense == TYPE_BABY) {
    return typeType ? 8.0 : 4.0; // extremly effective
  } else if (attack.damage.double.has(defense)) {
    return typeType ? 4.0 : 2.0; // very effective
  } else if (attack.damage.half.has(defense)) {
    return typeType ? 0.25 : 0.5; // not effective
  } else if (attack.damage.none.has(defense)) {
    return 0.0; // immune
  } else {
    return 1.0;
  }
}

export function getTypeMultiplier(attack: PokemonType, defender: PokemonType[]): number {
  var mult = 1.0;
  const tt = defender.includes(TYPE_TYPE);
  for (let type of defender) {
    mult *= getTypeMultiplierRaw(attack, type, tt);
  }
  if (defender.includes(TYPE_REVERSE)) {
    mult = (mult > 0) ? 1.0 / mult : 2.0;
  }
  return mult;
}

export const COLOR_RED = '#b0403a';
export const COLOR_ORANGE = '#F58331';
export const COLOR_YELLOW = '#FED431';
export const COLOR_BEIGE = '#E5C46A';
export const COLOR_LIGHT_BROWN = '#BDA439';
export const COLOR_BROWN = '#b08064';
export const COLOR_DARK_BROWN = '#73594A';
export const COLOR_GREEN_BROWN = '#ACBD20';
export const COLOR_GREEN = '#69AE46';
export const COLOR_LIGHT_GREEN = '#8fd66c';
export const COLOR_TEAL = '#54b096';
export const COLOR_BLUE = '#6A94F5';
export const COLOR_LIGHT_BLUE = '#9BDEDE';
export const COLOR_LIGHT_PINK = '#DD83BD';
export const COLOR_PINK = '#FF598A';
export const COLOR_LIGHT_PURPLE = '#AC94F6';
export const COLOR_PURPLE = '#A340A3';
export const COLOR_VIOLET = '#7238FF';
export const COLOR_DARK_VIOLET = '#675582';
export const COLOR_BLACK = '#242526';
export const COLOR_SILVER = '#BCBCD4';
export const COLOR_GREY = '#ACAC7A';


export const TYPE_ANCIENT:  PokemonType = { name: 'Ancient',  damage: emptyMult(), color: COLOR_LIGHT_BROWN };
export const TYPE_ANGRY:    PokemonType = { name: 'Angry',    damage: emptyMult(), color: COLOR_RED };
export const TYPE_BABY:     PokemonType = { name: 'Baby',     damage: emptyMult(), color: COLOR_LIGHT_BLUE };
export const TYPE_BAD:      PokemonType = { name: 'Bad',      damage: emptyMult(), color: COLOR_RED };
export const TYPE_BALL:     PokemonType = { name: 'Ball',     damage: emptyMult(), color: COLOR_TEAL };
export const TYPE_BEAN:     PokemonType = { name: 'Bean',     damage: emptyMult(), color: COLOR_GREEN_BROWN };
export const TYPE_BOOMER:   PokemonType = { name: 'Boomer',   damage: emptyMult(), color: COLOR_LIGHT_PURPLE };
export const TYPE_BORING:   PokemonType = { name: 'Boring',   damage: emptyMult(), color: COLOR_GREY};
export const TYPE_BUG:      PokemonType = { name: 'Bug',      damage: emptyMult(), color: COLOR_GREEN_BROWN };
export const TYPE_CRAB:     PokemonType = { name: 'Crab',     damage: emptyMult(), color: COLOR_BLUE };
export const TYPE_DANCE:    PokemonType = { name: 'Dance',    damage: emptyMult(), color: COLOR_GREEN };
export const TYPE_DARK:     PokemonType = { name: 'Dark',     damage: emptyMult(), color: COLOR_DARK_BROWN };
export const TYPE_DEEZNUTS: PokemonType = { name: 'Deez Nuts',damage: emptyMult(), color: COLOR_VIOLET };
export const TYPE_DRAGON:   PokemonType = { name: 'Dragon',   damage: emptyMult(), color: COLOR_VIOLET };
export const TYPE_DREAM:    PokemonType = { name: 'Dream',    damage: emptyMult(), color: COLOR_LIGHT_PURPLE };
export const TYPE_ELECTRIC: PokemonType = { name: 'Electric', damage: emptyMult(), color: COLOR_YELLOW };
export const TYPE_EMERALD:  PokemonType = { name: 'Emerald',  damage: emptyMult(), color: COLOR_LIGHT_GREEN };
export const TYPE_FAIRY:    PokemonType = { name: 'Fairy',    damage: emptyMult(), color: COLOR_LIGHT_PINK };
export const TYPE_FIGHTING: PokemonType = { name: 'Fighting', damage: emptyMult(), color: COLOR_RED };
export const TYPE_FIRE:     PokemonType = { name: 'Fire',     damage: emptyMult(), color: COLOR_ORANGE };
export const TYPE_FLUFFY:   PokemonType = { name: 'Fluffy',   damage: emptyMult(), color: COLOR_BEIGE };
export const TYPE_FLYING:   PokemonType = { name: 'Flying',   damage: emptyMult(), color: COLOR_LIGHT_PURPLE };
export const TYPE_FRIEND:   PokemonType = { name: 'Friend',   damage: emptyMult(), color: COLOR_LIGHT_GREEN };
export const TYPE_FURRY:    PokemonType = { name: 'Furry',    damage: emptyMult(), color: COLOR_BLUE };
export const TYPE_GAMER:    PokemonType = { name: 'Gamer',    damage: emptyMult(), color: COLOR_TEAL };
export const TYPE_GENDER:   PokemonType = { name: 'Gender',   damage: emptyMult(), color: COLOR_LIGHT_PINK };
export const TYPE_GHOST:    PokemonType = { name: 'Ghost',    damage: emptyMult(), color: COLOR_DARK_VIOLET };
export const TYPE_GRASS:    PokemonType = { name: 'Grass',    damage: emptyMult(), color: COLOR_GREEN };
export const TYPE_GROUND:   PokemonType = { name: 'Ground',   damage: emptyMult(), color: COLOR_BEIGE };
export const TYPE_GUN:      PokemonType = { name: 'Gun',      damage: emptyMult(), color: COLOR_ORANGE };
export const TYPE_GUYS:     PokemonType = { name: 'Guys',     damage: emptyMult(), color: COLOR_SILVER };
export const TYPE_ICE:      PokemonType = { name: 'Ice',      damage: emptyMult(), color: COLOR_LIGHT_BLUE };
export const TYPE_LEFT:     PokemonType = { name: 'Left',     damage: emptyMult(), color: COLOR_GREY };
export const TYPE_LIQUID:   PokemonType = { name: 'Liquid',   damage: emptyMult(), color: COLOR_LIGHT_BLUE };
export const TYPE_LITTLE:   PokemonType = { name: 'Little',   damage: emptyMult(), color: COLOR_LIGHT_GREEN };
export const TYPE_MAGIC:    PokemonType = { name: 'Magic',    damage: emptyMult(), color: COLOR_PINK };
export const TYPE_MONKE:    PokemonType = { name: 'Monke',    damage: emptyMult(), color: COLOR_LIGHT_BROWN };
export const TYPE_MYSTERY:  PokemonType = { name: 'Mystery',  damage: emptyMult(), color: '#EEEEEE' };
export const TYPE_NORMAL:   PokemonType = { name: 'Normal',   damage: emptyMult(), color: COLOR_GREY };
export const TYPE_NORMAL2:  PokemonType = { name: 'Normal2',  damage: emptyMult(), color: COLOR_GREY };
export const TYPE_OHIO:     PokemonType = { name: 'Ohio',     damage: emptyMult(), color: COLOR_PURPLE };
export const TYPE_OU:       PokemonType = { name: 'OU',       damage: emptyMult(), color: COLOR_TEAL };
export const TYPE_PIKACHU:  PokemonType = { name: 'Pikachu',  damage: emptyMult(), color: COLOR_YELLOW };
export const TYPE_POISON:   PokemonType = { name: 'Poison',   damage: emptyMult(), color: COLOR_PURPLE };
export const TYPE_PRIME:    PokemonType = { name: 'Prime',    damage: emptyMult(), color: COLOR_PURPLE };
export const TYPE_PSYCHIC:  PokemonType = { name: 'Psychic',  damage: emptyMult(), color: COLOR_PINK };
export const TYPE_REVERSE:  PokemonType = { name: 'Reverse',  damage: emptyMult(), color: COLOR_BLACK };
export const TYPE_RIGHT:    PokemonType = { name: 'Right',    damage: emptyMult(), color: COLOR_GREY };
export const TYPE_ROCK:     PokemonType = { name: 'Rock',     damage: emptyMult(), color: COLOR_LIGHT_BROWN };
export const TYPE_SANS:     PokemonType = { name: 'Sans',     damage: emptyMult(), color: COLOR_BLACK };
export const TYPE_SHARP:    PokemonType = { name: 'Sharp',    damage: emptyMult(), color: COLOR_SILVER };
export const TYPE_SILLY:    PokemonType = { name: 'Silly',    damage: emptyMult(), color: COLOR_LIGHT_PURPLE };
export const TYPE_SMASH:    PokemonType = { name: 'Smash',    damage: emptyMult(), color: COLOR_ORANGE };
export const TYPE_SONG:     PokemonType = { name: 'Song',     damage: emptyMult(), color: COLOR_BLUE };
export const TYPE_SPACE:    PokemonType = { name: 'Space',    damage: emptyMult(), color: COLOR_DARK_VIOLET };
export const TYPE_STEEL:    PokemonType = { name: 'Steel',    damage: emptyMult(), color: COLOR_SILVER };
export const TYPE_STINKY:   PokemonType = { name: 'Stinky',   damage: emptyMult(), color: COLOR_BROWN };
export const TYPE_SUS:      PokemonType = { name: 'Sus',      damage: emptyMult(), color: COLOR_DARK_BROWN };
export const TYPE_TYPE:     PokemonType = { name: 'Type',     damage: emptyMult(), color: COLOR_BLACK };
export const TYPE_UGLY:     PokemonType = { name: 'Ugly',     damage: emptyMult(), color: COLOR_DARK_VIOLET };
export const TYPE_VIBE:     PokemonType = { name: 'Vibe',     damage: emptyMult(), color: COLOR_VIOLET };
export const TYPE_WATER:    PokemonType = { name: 'Water',    damage: emptyMult(), color: COLOR_BLUE };
export const TYPE_ZOOMER:   PokemonType = { name: 'Zoomer',   damage: emptyMult(), color: COLOR_BLUE };

TYPE_ANCIENT.damage = { none: new Set([TYPE_CRAB, TYPE_SANS, TYPE_ZOOMER]), half: new Set([TYPE_ANCIENT, TYPE_BORING, TYPE_DREAM, TYPE_ELECTRIC, TYPE_EMERALD, TYPE_GRASS, TYPE_GUN, TYPE_ICE, TYPE_OHIO, TYPE_OU, TYPE_PIKACHU, TYPE_PRIME, TYPE_SONG, TYPE_UGLY]), double: new Set([TYPE_BABY, TYPE_DRAGON, TYPE_FIGHTING, TYPE_GHOST, TYPE_GROUND, TYPE_MAGIC, TYPE_MONKE, TYPE_ROCK, TYPE_SHARP, TYPE_SPACE, TYPE_STEEL, TYPE_STINKY, TYPE_VIBE]) };
TYPE_ANGRY.damage = { none: new Set([]), half: new Set([TYPE_ANCIENT, TYPE_BAD, TYPE_BEAN, TYPE_DANCE, TYPE_EMERALD, TYPE_FAIRY, TYPE_FIGHTING, TYPE_FLYING, TYPE_FURRY, TYPE_GHOST, TYPE_LIQUID, TYPE_MAGIC, TYPE_PRIME, TYPE_RIGHT, TYPE_SHARP, TYPE_SILLY, TYPE_SMASH, TYPE_SONG, TYPE_STEEL, TYPE_SUS, TYPE_WATER]), double: new Set([TYPE_ANGRY, TYPE_BABY, TYPE_BORING, TYPE_BUG, TYPE_DARK, TYPE_DREAM, TYPE_ELECTRIC, TYPE_FIRE, TYPE_GAMER, TYPE_GROUND, TYPE_GUYS, TYPE_ICE, TYPE_LEFT, TYPE_OHIO, TYPE_OU, TYPE_PIKACHU, TYPE_POISON, TYPE_PSYCHIC, TYPE_ROCK, TYPE_SANS, TYPE_VIBE, TYPE_ZOOMER]) };
TYPE_BABY.damage = { none: new Set([TYPE_DEEZNUTS, TYPE_SANS]), half: new Set([TYPE_EMERALD]), double: new Set([]) };
TYPE_BAD.damage = { none: new Set([]), half: new Set([TYPE_BAD, TYPE_DEEZNUTS, TYPE_EMERALD, TYPE_FAIRY, TYPE_FIGHTING, TYPE_FRIEND, TYPE_POISON, TYPE_PSYCHIC, TYPE_ROCK, TYPE_SILLY, TYPE_STEEL]), double: new Set([TYPE_BABY, TYPE_BOOMER, TYPE_BORING, TYPE_DARK, TYPE_ELECTRIC, TYPE_FIRE, TYPE_GENDER, TYPE_GRASS, TYPE_GUN, TYPE_LITTLE, TYPE_NORMAL, TYPE_NORMAL2, TYPE_OU, TYPE_PIKACHU, TYPE_PRIME, TYPE_SANS, TYPE_UGLY, TYPE_VIBE]) };
TYPE_BALL.damage = { none: new Set([TYPE_SANS]), half: new Set([TYPE_DEEZNUTS, TYPE_EMERALD, TYPE_RIGHT, TYPE_SILLY]), double: new Set([TYPE_ANCIENT, TYPE_BABY, TYPE_BAD, TYPE_BALL, TYPE_BOOMER, TYPE_BORING, TYPE_GAMER, TYPE_VIBE]) };
TYPE_BEAN.damage = { none: new Set([TYPE_BEAN, TYPE_SANS]), half: new Set([TYPE_BAD, TYPE_BOOMER, TYPE_BORING, TYPE_DANCE, TYPE_EMERALD, TYPE_FIRE, TYPE_ICE, TYPE_LITTLE, TYPE_SILLY, TYPE_SONG, TYPE_SPACE, TYPE_STEEL, TYPE_SUS]), double: new Set([TYPE_ANCIENT, TYPE_ANGRY, TYPE_BABY, TYPE_FAIRY, TYPE_GRASS, TYPE_GROUND, TYPE_MAGIC, TYPE_MONKE, TYPE_OHIO, TYPE_POISON, TYPE_PRIME, TYPE_ROCK, TYPE_ZOOMER]) };
TYPE_BOOMER.damage = { none: new Set([TYPE_SANS]), half: new Set([TYPE_DRAGON, TYPE_EMERALD, TYPE_FAIRY, TYPE_FIGHTING, TYPE_GAMER, TYPE_GENDER, TYPE_LEFT, TYPE_MAGIC, TYPE_PRIME, TYPE_PSYCHIC, TYPE_SMASH, TYPE_SONG, TYPE_SPACE, TYPE_STINKY, TYPE_VIBE, TYPE_ZOOMER]), double: new Set([TYPE_BABY, TYPE_BEAN, TYPE_BORING, TYPE_DANCE, TYPE_FIRE, TYPE_GRASS, TYPE_GUN, TYPE_RIGHT, TYPE_STEEL, TYPE_UGLY, TYPE_WATER]) };
TYPE_BORING.damage = { none: new Set([TYPE_SANS]), half: new Set([TYPE_BEAN, TYPE_BOOMER, TYPE_BORING, TYPE_ELECTRIC, TYPE_EMERALD, TYPE_FAIRY, TYPE_FIGHTING, TYPE_FIRE, TYPE_FRIEND, TYPE_GUYS, TYPE_PIKACHU, TYPE_PRIME, TYPE_ROCK, TYPE_SMASH, TYPE_UGLY]), double: new Set([TYPE_BABY, TYPE_FURRY, TYPE_MAGIC, TYPE_STINKY, TYPE_VIBE]) };
TYPE_BUG.damage = { none: new Set([TYPE_SANS]), half: new Set([TYPE_ANCIENT, TYPE_DANCE, TYPE_EMERALD, TYPE_FAIRY, TYPE_FIGHTING, TYPE_FIRE, TYPE_FLUFFY, TYPE_FLYING, TYPE_GHOST, TYPE_POISON, TYPE_STEEL, TYPE_VIBE]), double: new Set([TYPE_BABY, TYPE_BEAN, TYPE_BORING, TYPE_DARK, TYPE_GRASS, TYPE_LITTLE, TYPE_PSYCHIC, TYPE_ZOOMER]) };
TYPE_CRAB.damage = { none: new Set([TYPE_SANS]), half: new Set([TYPE_CRAB, TYPE_EMERALD, TYPE_FIRE, TYPE_GAMER, TYPE_GRASS, TYPE_OHIO, TYPE_SHARP, TYPE_SONG, TYPE_WATER]), double: new Set([TYPE_ANGRY, TYPE_BABY, TYPE_BORING, TYPE_DANCE, TYPE_DEEZNUTS, TYPE_FIGHTING, TYPE_UGLY]) };
TYPE_DANCE.damage = { none: new Set([TYPE_SANS]), half: new Set([TYPE_ANCIENT, TYPE_CRAB, TYPE_DANCE, TYPE_EMERALD, TYPE_FIGHTING, TYPE_FURRY, TYPE_GUN, TYPE_POISON, TYPE_PRIME, TYPE_STINKY, TYPE_SUS]), double: new Set([TYPE_ANGRY, TYPE_BABY, TYPE_BALL, TYPE_BOOMER, TYPE_FIRE, TYPE_FRIEND, TYPE_GHOST, TYPE_GUYS, TYPE_ICE, TYPE_MONKE, TYPE_SONG, TYPE_VIBE, TYPE_WATER]) };
TYPE_DARK.damage = { none: new Set([TYPE_FRIEND, TYPE_GAMER, TYPE_SPACE]), half: new Set([TYPE_BAD, TYPE_DARK, TYPE_DEEZNUTS, TYPE_DREAM, TYPE_EMERALD, TYPE_FAIRY, TYPE_FIGHTING, TYPE_MONKE, TYPE_RIGHT, TYPE_SMASH, TYPE_SUS, TYPE_UGLY]), double: new Set([TYPE_BABY, TYPE_FURRY, TYPE_GHOST, TYPE_PSYCHIC, TYPE_SANS, TYPE_SILLY, TYPE_VIBE]) };
TYPE_DEEZNUTS.damage = { none: new Set([TYPE_SANS]), half: new Set([TYPE_BAD, TYPE_EMERALD, TYPE_FIGHTING, TYPE_FLUFFY, TYPE_FLYING, TYPE_FURRY, TYPE_GENDER, TYPE_PRIME, TYPE_SHARP, TYPE_STINKY]), double: new Set([TYPE_ANGRY, TYPE_BABY, TYPE_BOOMER, TYPE_BORING, TYPE_DANCE, TYPE_DARK, TYPE_DEEZNUTS, TYPE_ELECTRIC, TYPE_GUYS, TYPE_LEFT, TYPE_PIKACHU, TYPE_PSYCHIC, TYPE_RIGHT]) };
TYPE_DRAGON.damage = { none: new Set([TYPE_FAIRY, TYPE_SANS]), half: new Set([TYPE_BALL, TYPE_EMERALD, TYPE_FRIEND, TYPE_GUN, TYPE_MAGIC, TYPE_OU, TYPE_PRIME, TYPE_SILLY, TYPE_STEEL]), double: new Set([TYPE_ANCIENT, TYPE_BABY, TYPE_BOOMER, TYPE_BORING, TYPE_DEEZNUTS, TYPE_DRAGON, TYPE_FURRY, TYPE_LITTLE, TYPE_OHIO, TYPE_SMASH]) };
TYPE_DREAM.damage = { none: new Set([TYPE_SANS]), half: new Set([TYPE_ANCIENT, TYPE_DREAM, TYPE_EMERALD, TYPE_LEFT, TYPE_MAGIC, TYPE_PRIME, TYPE_RIGHT, TYPE_ROCK]), double: new Set([TYPE_BABY, TYPE_DARK, TYPE_GAMER, TYPE_GHOST, TYPE_GUYS, TYPE_PSYCHIC, TYPE_SONG]) };
TYPE_ELECTRIC.damage = { none: new Set([TYPE_GROUND, TYPE_SANS, TYPE_SPACE, TYPE_ZOOMER]), half: new Set([TYPE_BALL, TYPE_BOOMER, TYPE_DANCE, TYPE_DRAGON, TYPE_ELECTRIC, TYPE_EMERALD, TYPE_FLUFFY, TYPE_GAMER, TYPE_GRASS, TYPE_MAGIC, TYPE_OHIO, TYPE_OU, TYPE_PIKACHU, TYPE_SILLY]), double: new Set([TYPE_ANGRY, TYPE_BABY, TYPE_BAD, TYPE_BORING, TYPE_DREAM, TYPE_FLYING, TYPE_GUN, TYPE_LIQUID, TYPE_PRIME, TYPE_WATER]) };
TYPE_EMERALD.damage = { none: new Set([]), half: new Set([]), double: new Set([TYPE_ANCIENT, TYPE_ANGRY, TYPE_BABY, TYPE_BAD, TYPE_BALL, TYPE_BEAN, TYPE_BOOMER, TYPE_BORING, TYPE_BUG, TYPE_CRAB, TYPE_DANCE, TYPE_DARK, TYPE_DEEZNUTS, TYPE_DRAGON, TYPE_DREAM, TYPE_ELECTRIC, TYPE_EMERALD, TYPE_FAIRY, TYPE_FIGHTING, TYPE_FIRE, TYPE_FLUFFY, TYPE_FLYING, TYPE_FRIEND, TYPE_FURRY, TYPE_GAMER, TYPE_GENDER, TYPE_GHOST, TYPE_GRASS, TYPE_GROUND, TYPE_GUN, TYPE_GUYS, TYPE_ICE, TYPE_LEFT, TYPE_LIQUID, TYPE_LITTLE, TYPE_MAGIC, TYPE_MONKE, TYPE_NORMAL, TYPE_NORMAL2, TYPE_OHIO, TYPE_OU, TYPE_PIKACHU, TYPE_POISON, TYPE_PRIME, TYPE_PSYCHIC, TYPE_RIGHT, TYPE_ROCK, TYPE_SANS, TYPE_SHARP, TYPE_SILLY, TYPE_SMASH, TYPE_SONG, TYPE_SPACE, TYPE_STEEL, TYPE_STINKY, TYPE_SUS, TYPE_TYPE, TYPE_UGLY, TYPE_VIBE, TYPE_WATER, TYPE_ZOOMER]) };
TYPE_FAIRY.damage = { none: new Set([TYPE_SANS]), half: new Set([TYPE_CRAB, TYPE_DEEZNUTS, TYPE_EMERALD, TYPE_FIRE, TYPE_GAMER, TYPE_GUN, TYPE_OHIO, TYPE_POISON, TYPE_SILLY, TYPE_SONG, TYPE_STEEL, TYPE_STINKY, TYPE_VIBE]), double: new Set([TYPE_ANGRY, TYPE_BABY, TYPE_BEAN, TYPE_BOOMER, TYPE_DARK, TYPE_DRAGON, TYPE_DREAM, TYPE_FIGHTING, TYPE_GENDER, TYPE_LITTLE, TYPE_MAGIC, TYPE_UGLY]) };
TYPE_FIGHTING.damage = { none: new Set([TYPE_GHOST, TYPE_GUN, TYPE_SANS]), half: new Set([TYPE_BEAN, TYPE_BUG, TYPE_DANCE, TYPE_EMERALD, TYPE_FAIRY, TYPE_FLYING, TYPE_FRIEND, TYPE_MONKE, TYPE_POISON, TYPE_PRIME, TYPE_PSYCHIC, TYPE_SPACE]), double: new Set([TYPE_ANGRY, TYPE_BABY, TYPE_BOOMER, TYPE_DARK, TYPE_DEEZNUTS, TYPE_FURRY, TYPE_ICE, TYPE_LITTLE, TYPE_NORMAL, TYPE_NORMAL2, TYPE_RIGHT, TYPE_ROCK, TYPE_SMASH, TYPE_STEEL]) };
TYPE_FIRE.damage = { none: new Set([TYPE_OHIO, TYPE_SANS]), half: new Set([TYPE_BAD, TYPE_BALL, TYPE_BOOMER, TYPE_DANCE, TYPE_DRAGON, TYPE_EMERALD, TYPE_FIRE, TYPE_LIQUID, TYPE_MAGIC, TYPE_PRIME, TYPE_ROCK, TYPE_SONG, TYPE_WATER]), double: new Set([TYPE_ANCIENT, TYPE_ANGRY, TYPE_BABY, TYPE_BORING, TYPE_BUG, TYPE_CRAB, TYPE_DEEZNUTS, TYPE_FLUFFY, TYPE_FURRY, TYPE_GRASS, TYPE_ICE, TYPE_MONKE, TYPE_SMASH, TYPE_STEEL, TYPE_STINKY]) };
TYPE_FLUFFY.damage = { none: new Set([TYPE_SANS]), half: new Set([TYPE_BORING, TYPE_DREAM, TYPE_EMERALD, TYPE_FIRE, TYPE_FLUFFY]), double: new Set([TYPE_ANGRY, TYPE_BABY, TYPE_DARK, TYPE_FURRY, TYPE_ICE, TYPE_UGLY, TYPE_WATER]) };
TYPE_FLYING.damage = { none: new Set([TYPE_SANS]), half: new Set([TYPE_ELECTRIC, TYPE_EMERALD, TYPE_FLUFFY, TYPE_OU, TYPE_PIKACHU, TYPE_ROCK, TYPE_SHARP, TYPE_STEEL]), double: new Set([TYPE_ANGRY, TYPE_BABY, TYPE_BEAN, TYPE_BOOMER, TYPE_BUG, TYPE_CRAB, TYPE_FIGHTING, TYPE_GRASS, TYPE_GUYS, TYPE_MONKE, TYPE_OHIO]) };
TYPE_FRIEND.damage = { none: new Set([TYPE_RIGHT]), half: new Set([TYPE_BORING, TYPE_EMERALD, TYPE_FURRY, TYPE_GAMER, TYPE_GENDER, TYPE_LIQUID, TYPE_MONKE, TYPE_POISON, TYPE_PRIME, TYPE_ROCK, TYPE_SONG, TYPE_STEEL, TYPE_STINKY, TYPE_SUS, TYPE_UGLY]), double: new Set([TYPE_ANGRY, TYPE_BABY, TYPE_BALL, TYPE_BUG, TYPE_CRAB, TYPE_DARK, TYPE_DRAGON, TYPE_FIGHTING, TYPE_FRIEND, TYPE_GHOST, TYPE_GUYS, TYPE_MAGIC, TYPE_PSYCHIC, TYPE_SANS, TYPE_SILLY, TYPE_ZOOMER]) };
TYPE_FURRY.damage = { none: new Set([TYPE_SANS]), half: new Set([TYPE_BALL, TYPE_EMERALD, TYPE_FIGHTING, TYPE_GAMER, TYPE_GENDER, TYPE_NORMAL, TYPE_NORMAL2, TYPE_RIGHT, TYPE_SPACE]), double: new Set([TYPE_ANGRY, TYPE_BABY, TYPE_BOOMER, TYPE_DANCE, TYPE_DEEZNUTS, TYPE_FLUFFY, TYPE_FRIEND, TYPE_GRASS, TYPE_OHIO, TYPE_SONG, TYPE_STINKY, TYPE_ZOOMER]) };
TYPE_GAMER.damage = { none: new Set([TYPE_GRASS]), half: new Set([TYPE_BAD, TYPE_DEEZNUTS, TYPE_ELECTRIC, TYPE_EMERALD, TYPE_FAIRY, TYPE_FIGHTING, TYPE_FRIEND, TYPE_FURRY, TYPE_GENDER, TYPE_LIQUID, TYPE_NORMAL, TYPE_NORMAL2, TYPE_OU, TYPE_PIKACHU, TYPE_STINKY, TYPE_WATER]), double: new Set([TYPE_ANGRY, TYPE_BABY, TYPE_BOOMER, TYPE_BUG, TYPE_DARK, TYPE_GAMER, TYPE_GUYS, TYPE_POISON, TYPE_PRIME, TYPE_RIGHT, TYPE_SANS, TYPE_SUS, TYPE_ZOOMER]) };
TYPE_GENDER.damage = { none: new Set([TYPE_SANS]), half: new Set([TYPE_DEEZNUTS, TYPE_EMERALD, TYPE_FAIRY, TYPE_FIGHTING, TYPE_FIRE, TYPE_FLUFFY, TYPE_FRIEND, TYPE_POISON, TYPE_PSYCHIC, TYPE_SONG, TYPE_STEEL, TYPE_STINKY, TYPE_SUS]), double: new Set([TYPE_ANCIENT, TYPE_BABY, TYPE_BAD, TYPE_BUG, TYPE_DARK, TYPE_DRAGON, TYPE_GAMER, TYPE_GENDER, TYPE_GHOST, TYPE_GRASS, TYPE_LEFT, TYPE_LIQUID, TYPE_MAGIC, TYPE_MONKE, TYPE_NORMAL, TYPE_NORMAL2, TYPE_OHIO, TYPE_RIGHT, TYPE_SILLY, TYPE_UGLY, TYPE_VIBE, TYPE_WATER, TYPE_ZOOMER]) };
TYPE_GHOST.damage = { none: new Set([TYPE_NORMAL, TYPE_NORMAL2, TYPE_SPACE, TYPE_SUS]), half: new Set([TYPE_DARK, TYPE_EMERALD, TYPE_FRIEND, TYPE_GUN, TYPE_GUYS, TYPE_OHIO, TYPE_SONG, TYPE_UGLY]), double: new Set([TYPE_ANCIENT, TYPE_BABY, TYPE_BORING, TYPE_DREAM, TYPE_GAMER, TYPE_GHOST, TYPE_MAGIC, TYPE_PSYCHIC, TYPE_SANS]) };
TYPE_GRASS.damage = { none: new Set([TYPE_SANS]), half: new Set([TYPE_ANGRY, TYPE_BEAN, TYPE_BUG, TYPE_DRAGON, TYPE_EMERALD, TYPE_FIRE, TYPE_FLYING, TYPE_FURRY, TYPE_GRASS, TYPE_LEFT, TYPE_POISON, TYPE_STEEL, TYPE_VIBE]), double: new Set([TYPE_BABY, TYPE_GAMER, TYPE_GROUND, TYPE_LIQUID, TYPE_MONKE, TYPE_OHIO, TYPE_RIGHT, TYPE_ROCK, TYPE_WATER]) };
TYPE_GROUND.damage = { none: new Set([TYPE_FLYING, TYPE_SANS]), half: new Set([TYPE_BEAN, TYPE_BOOMER, TYPE_BUG, TYPE_DEEZNUTS, TYPE_EMERALD, TYPE_GRASS, TYPE_MONKE, TYPE_PIKACHU]), double: new Set([TYPE_BABY, TYPE_ELECTRIC, TYPE_FIRE, TYPE_GUN, TYPE_LIQUID, TYPE_OHIO, TYPE_OU, TYPE_POISON, TYPE_ROCK, TYPE_SHARP, TYPE_SPACE, TYPE_STEEL]) };
TYPE_GUN.damage = { none: new Set([TYPE_RIGHT, TYPE_SANS]), half: new Set([TYPE_BAD, TYPE_BEAN, TYPE_EMERALD, TYPE_FLUFFY, TYPE_FLYING, TYPE_GHOST, TYPE_LITTLE, TYPE_MAGIC, TYPE_OHIO, TYPE_ROCK, TYPE_STEEL, TYPE_WATER]), double: new Set([TYPE_BABY, TYPE_BORING, TYPE_DEEZNUTS, TYPE_FIGHTING, TYPE_FRIEND, TYPE_FURRY, TYPE_LEFT, TYPE_MONKE, TYPE_SILLY, TYPE_VIBE]) };
TYPE_GUYS.damage = { none: new Set([TYPE_GHOST, TYPE_SPACE]), half: new Set([TYPE_EMERALD, TYPE_FLUFFY, TYPE_FRIEND, TYPE_GUYS, TYPE_LEFT, TYPE_MAGIC, TYPE_POISON, TYPE_SHARP, TYPE_SILLY, TYPE_STEEL, TYPE_STINKY]), double: new Set([TYPE_ANGRY, TYPE_BABY, TYPE_BALL, TYPE_BORING, TYPE_DARK, TYPE_FIGHTING, TYPE_FIRE, TYPE_FURRY, TYPE_RIGHT, TYPE_SANS, TYPE_SONG, TYPE_SUS, TYPE_VIBE]) };
TYPE_ICE.damage = { none: new Set([TYPE_FLUFFY, TYPE_SANS]), half: new Set([TYPE_BAD, TYPE_EMERALD, TYPE_FIRE, TYPE_FURRY, TYPE_ICE, TYPE_SPACE, TYPE_STEEL, TYPE_WATER]), double: new Set([TYPE_ANGRY, TYPE_BABY, TYPE_BEAN, TYPE_CRAB, TYPE_DANCE, TYPE_DEEZNUTS, TYPE_DRAGON, TYPE_FLYING, TYPE_FRIEND, TYPE_GRASS, TYPE_GROUND, TYPE_LIQUID, TYPE_PRIME, TYPE_STINKY, TYPE_VIBE]) };
TYPE_LEFT.damage = { none: new Set([TYPE_SANS]), half: new Set([TYPE_BEAN, TYPE_BOOMER, TYPE_DREAM, TYPE_EMERALD, TYPE_FIGHTING, TYPE_MAGIC, TYPE_MONKE, TYPE_OHIO, TYPE_PSYCHIC, TYPE_RIGHT, TYPE_SILLY, TYPE_SMASH, TYPE_ZOOMER]), double: new Set([TYPE_ANGRY, TYPE_DEEZNUTS, TYPE_ELECTRIC, TYPE_FAIRY, TYPE_FIRE, TYPE_FRIEND, TYPE_GENDER, TYPE_GHOST, TYPE_GRASS, TYPE_GUYS, TYPE_PIKACHU, TYPE_SONG, TYPE_VIBE, TYPE_WATER]) };
TYPE_LIQUID.damage = { none: new Set([TYPE_MONKE, TYPE_POISON, TYPE_SANS]), half: new Set([TYPE_BEAN, TYPE_BORING, TYPE_CRAB, TYPE_DANCE, TYPE_EMERALD, TYPE_GRASS, TYPE_GUYS, TYPE_LIQUID, TYPE_WATER]), double: new Set([TYPE_BABY, TYPE_BUG, TYPE_FIGHTING, TYPE_FLYING, TYPE_GAMER, TYPE_GROUND, TYPE_ROCK, TYPE_SPACE, TYPE_STINKY]) };
TYPE_LITTLE.damage = { none: new Set([TYPE_DEEZNUTS, TYPE_SANS, TYPE_SMASH]), half: new Set([TYPE_BEAN, TYPE_EMERALD, TYPE_FIGHTING, TYPE_LITTLE]), double: new Set([TYPE_ANGRY, TYPE_BABY, TYPE_BALL, TYPE_CRAB, TYPE_FAIRY, TYPE_FRIEND, TYPE_ZOOMER]) };
TYPE_MAGIC.damage = { none: new Set([TYPE_OHIO, TYPE_SANS]), half: new Set([TYPE_DEEZNUTS, TYPE_EMERALD, TYPE_FAIRY, TYPE_FRIEND, TYPE_GUN, TYPE_MAGIC, TYPE_MONKE, TYPE_POISON, TYPE_SILLY, TYPE_SPACE]), double: new Set([TYPE_ANCIENT, TYPE_BABY, TYPE_BEAN, TYPE_BOOMER, TYPE_BORING, TYPE_DANCE, TYPE_DRAGON, TYPE_DREAM, TYPE_ELECTRIC, TYPE_GHOST, TYPE_NORMAL, TYPE_NORMAL2, TYPE_OU, TYPE_PIKACHU]) };
TYPE_MONKE.damage = { none: new Set([TYPE_SANS]), half: new Set([TYPE_ELECTRIC, TYPE_EMERALD, TYPE_FIRE, TYPE_FLUFFY, TYPE_FLYING, TYPE_GHOST, TYPE_LITTLE, TYPE_OU, TYPE_PIKACHU, TYPE_POISON, TYPE_PSYCHIC, TYPE_STEEL, TYPE_SUS]), double: new Set([TYPE_ANCIENT, TYPE_ANGRY, TYPE_BABY, TYPE_BEAN, TYPE_BORING, TYPE_BUG, TYPE_DANCE, TYPE_FIGHTING, TYPE_FURRY, TYPE_GUYS, TYPE_NORMAL, TYPE_NORMAL2, TYPE_RIGHT, TYPE_SMASH, TYPE_STINKY, TYPE_VIBE]) };
TYPE_MYSTERY.damage = { none: new Set([]), half: new Set([]), double: new Set([TYPE_SANS]) };
TYPE_NORMAL.damage = { none: new Set([TYPE_GHOST, TYPE_SANS]), half: new Set([TYPE_ANGRY, TYPE_BORING, TYPE_EMERALD, TYPE_NORMAL2, TYPE_ROCK, TYPE_STEEL]), double: new Set([TYPE_BABY, TYPE_FURRY, TYPE_SUS]) };
TYPE_NORMAL2.damage = { none: new Set([TYPE_GHOST]), half: new Set([TYPE_ANGRY, TYPE_BALL, TYPE_BORING, TYPE_EMERALD, TYPE_NORMAL2, TYPE_ROCK, TYPE_STEEL]), double: new Set([TYPE_BABY, TYPE_FURRY, TYPE_NORMAL, TYPE_SANS, TYPE_SUS]) };
TYPE_OHIO.damage = { none: new Set([TYPE_SANS]), half: new Set([TYPE_DARK, TYPE_DRAGON, TYPE_EMERALD, TYPE_FIRE, TYPE_FLYING, TYPE_GRASS, TYPE_MAGIC, TYPE_SUS]), double: new Set([TYPE_BABY, TYPE_BOOMER, TYPE_FURRY, TYPE_GHOST, TYPE_GUN, TYPE_GUYS, TYPE_NORMAL, TYPE_NORMAL2, TYPE_POISON, TYPE_RIGHT, TYPE_SPACE, TYPE_VIBE]) };
TYPE_OU.damage = { none: new Set([TYPE_SANS]), half: new Set([TYPE_EMERALD]), double: new Set([TYPE_ANGRY, TYPE_BABY, TYPE_BAD, TYPE_BORING, TYPE_DANCE, TYPE_DRAGON, TYPE_DREAM, TYPE_FLYING, TYPE_FRIEND, TYPE_GRASS, TYPE_GROUND, TYPE_GUN, TYPE_LIQUID, TYPE_LITTLE, TYPE_OHIO, TYPE_STINKY, TYPE_VIBE, TYPE_WATER]) };
TYPE_PIKACHU.damage = { none: new Set([TYPE_FLYING, TYPE_SANS, TYPE_SPACE, TYPE_ZOOMER]), half: new Set([TYPE_BALL, TYPE_BOOMER, TYPE_DANCE, TYPE_DRAGON, TYPE_ELECTRIC, TYPE_EMERALD, TYPE_FLUFFY, TYPE_GAMER, TYPE_GRASS, TYPE_MAGIC, TYPE_OHIO, TYPE_OU, TYPE_PIKACHU, TYPE_SILLY]), double: new Set([TYPE_ANGRY, TYPE_BABY, TYPE_BAD, TYPE_BORING, TYPE_DREAM, TYPE_GROUND, TYPE_GUN, TYPE_LIQUID, TYPE_PRIME, TYPE_WATER]) };
TYPE_POISON.damage = { none: new Set([TYPE_SANS, TYPE_STEEL]), half: new Set([TYPE_BORING, TYPE_DEEZNUTS, TYPE_EMERALD, TYPE_GHOST, TYPE_GROUND, TYPE_GUN, TYPE_POISON, TYPE_PRIME, TYPE_RIGHT, TYPE_ROCK, TYPE_SPACE, TYPE_STINKY, TYPE_SUS, TYPE_UGLY]), double: new Set([TYPE_ANGRY, TYPE_BABY, TYPE_BOOMER, TYPE_FAIRY, TYPE_FRIEND, TYPE_GENDER, TYPE_GRASS, TYPE_GUYS, TYPE_MAGIC, TYPE_SILLY, TYPE_VIBE]) };
TYPE_PRIME.damage = { none: new Set([TYPE_ANCIENT]), half: new Set([TYPE_DARK, TYPE_DEEZNUTS, TYPE_EMERALD, TYPE_FIGHTING, TYPE_GUN, TYPE_LIQUID, TYPE_MAGIC, TYPE_STEEL, TYPE_SUS]), double: new Set([TYPE_BABY, TYPE_BORING, TYPE_CRAB, TYPE_ELECTRIC, TYPE_FAIRY, TYPE_FRIEND, TYPE_GAMER, TYPE_GROUND, TYPE_GUYS, TYPE_PIKACHU, TYPE_PRIME, TYPE_SANS, TYPE_SILLY, TYPE_UGLY, TYPE_VIBE, TYPE_WATER, TYPE_ZOOMER]) };
TYPE_PSYCHIC.damage = { none: new Set([TYPE_DARK, TYPE_SANS]), half: new Set([TYPE_BALL, TYPE_BORING, TYPE_EMERALD, TYPE_FRIEND, TYPE_GUYS, TYPE_MAGIC, TYPE_PSYCHIC, TYPE_STEEL]), double: new Set([TYPE_ANCIENT, TYPE_ANGRY, TYPE_BABY, TYPE_DREAM, TYPE_FIGHTING, TYPE_POISON, TYPE_RIGHT, TYPE_SPACE, TYPE_SUS, TYPE_VIBE]) };
TYPE_REVERSE.damage = { none: new Set([TYPE_SANS]), half: new Set([]), double: new Set([]) };
TYPE_RIGHT.damage = { none: new Set([TYPE_SANS]), half: new Set([TYPE_BAD, TYPE_DREAM, TYPE_ELECTRIC, TYPE_EMERALD, TYPE_FAIRY, TYPE_FRIEND, TYPE_FURRY, TYPE_GAMER, TYPE_GUN, TYPE_LEFT, TYPE_MAGIC, TYPE_MONKE, TYPE_OU, TYPE_PIKACHU, TYPE_PSYCHIC, TYPE_SILLY, TYPE_VIBE]), double: new Set([TYPE_BOOMER, TYPE_DEEZNUTS, TYPE_GENDER, TYPE_GUYS, TYPE_NORMAL, TYPE_NORMAL2, TYPE_OHIO, TYPE_ROCK, TYPE_STEEL, TYPE_UGLY]) };
TYPE_ROCK.damage = { none: new Set([TYPE_SANS]), half: new Set([TYPE_EMERALD, TYPE_FIGHTING, TYPE_GROUND, TYPE_LIQUID, TYPE_STEEL]), double: new Set([TYPE_ANCIENT, TYPE_BABY, TYPE_BOOMER, TYPE_BUG, TYPE_DEEZNUTS, TYPE_FIRE, TYPE_FLYING, TYPE_ICE, TYPE_SILLY, TYPE_SMASH, TYPE_SONG, TYPE_ZOOMER]) };
TYPE_SANS.damage = { none: new Set([]), half: new Set([]), double: new Set([TYPE_SANS]) };
TYPE_SHARP.damage = { none: new Set([]), half: new Set([TYPE_BEAN, TYPE_EMERALD, TYPE_GUN, TYPE_LIQUID, TYPE_OHIO, TYPE_ROCK, TYPE_SPACE, TYPE_STEEL]), double: new Set([TYPE_BABY, TYPE_CRAB, TYPE_FLUFFY, TYPE_FLYING, TYPE_FRIEND, TYPE_FURRY, TYPE_GRASS, TYPE_ICE, TYPE_NORMAL, TYPE_NORMAL2, TYPE_SANS, TYPE_SHARP, TYPE_SILLY, TYPE_ZOOMER]) };
TYPE_SILLY.damage = { none: new Set([TYPE_GUYS, TYPE_SANS]), half: new Set([TYPE_ANCIENT, TYPE_BUG, TYPE_EMERALD, TYPE_FLUFFY, TYPE_FRIEND, TYPE_FURRY, TYPE_GHOST, TYPE_GUN, TYPE_PSYCHIC, TYPE_ROCK, TYPE_SHARP, TYPE_SUS, TYPE_ZOOMER]), double: new Set([TYPE_ANGRY, TYPE_BABY, TYPE_BEAN, TYPE_BORING, TYPE_DARK, TYPE_DRAGON, TYPE_DREAM, TYPE_GENDER, TYPE_GRASS, TYPE_LIQUID, TYPE_MONKE, TYPE_POISON, TYPE_PRIME, TYPE_SILLY, TYPE_SONG, TYPE_STINKY, TYPE_WATER]) };
TYPE_SMASH.damage = { none: new Set([TYPE_LITTLE]), half: new Set([TYPE_ANCIENT, TYPE_BAD, TYPE_BEAN, TYPE_BORING, TYPE_EMERALD, TYPE_GAMER, TYPE_GENDER, TYPE_RIGHT, TYPE_SILLY, TYPE_STINKY, TYPE_UGLY]), double: new Set([TYPE_ANGRY, TYPE_BABY, TYPE_BALL, TYPE_DEEZNUTS, TYPE_FRIEND, TYPE_FURRY, TYPE_GUYS, TYPE_ICE, TYPE_ROCK, TYPE_SANS, TYPE_STEEL, TYPE_VIBE]) };
TYPE_SONG.damage = { none: new Set([TYPE_SANS]), half: new Set([TYPE_BAD, TYPE_EMERALD, TYPE_FAIRY, TYPE_GUN, TYPE_MONKE]), double: new Set([TYPE_ANCIENT, TYPE_BABY, TYPE_BORING, TYPE_CRAB, TYPE_DANCE, TYPE_DRAGON, TYPE_FRIEND, TYPE_LIQUID, TYPE_OHIO, TYPE_VIBE]) };
TYPE_SPACE.damage = { none: new Set([TYPE_SANS]), half: new Set([TYPE_BAD, TYPE_BEAN, TYPE_DARK, TYPE_DREAM, TYPE_EMERALD, TYPE_ICE, TYPE_OU, TYPE_SPACE, TYPE_VIBE]), double: new Set([TYPE_ANCIENT, TYPE_BABY, TYPE_BORING, TYPE_ELECTRIC, TYPE_FIRE, TYPE_MAGIC, TYPE_NORMAL, TYPE_NORMAL2, TYPE_PIKACHU, TYPE_PSYCHIC, TYPE_STINKY]) };
TYPE_STEEL.damage = { none: new Set([]), half: new Set([TYPE_ELECTRIC, TYPE_EMERALD, TYPE_FIRE, TYPE_LIQUID, TYPE_OHIO, TYPE_OU, TYPE_PIKACHU, TYPE_STEEL, TYPE_WATER]), double: new Set([TYPE_ANGRY, TYPE_BABY, TYPE_DEEZNUTS, TYPE_FAIRY, TYPE_ICE, TYPE_RIGHT, TYPE_ROCK, TYPE_SANS]) };
TYPE_STINKY.damage = { none: new Set([TYPE_FURRY, TYPE_GAMER, TYPE_MONKE, TYPE_SANS, TYPE_STEEL]), half: new Set([TYPE_BAD, TYPE_BORING, TYPE_CRAB, TYPE_DANCE, TYPE_EMERALD, TYPE_FAIRY, TYPE_FLUFFY, TYPE_GHOST, TYPE_GROUND, TYPE_OHIO, TYPE_POISON, TYPE_ROCK, TYPE_SHARP, TYPE_STINKY, TYPE_SUS]), double: new Set([TYPE_ANCIENT, TYPE_ANGRY, TYPE_BABY, TYPE_DEEZNUTS, TYPE_DRAGON, TYPE_FLYING, TYPE_FRIEND, TYPE_GENDER, TYPE_GUYS, TYPE_PRIME, TYPE_PSYCHIC, TYPE_RIGHT, TYPE_SILLY, TYPE_SMASH, TYPE_SPACE, TYPE_UGLY, TYPE_VIBE, TYPE_ZOOMER]) };
TYPE_SUS.damage = { none: new Set([]), half: new Set([TYPE_BALL, TYPE_EMERALD, TYPE_GENDER, TYPE_GHOST, TYPE_PRIME, TYPE_PSYCHIC, TYPE_SUS, TYPE_VIBE]), double: new Set([TYPE_ANGRY, TYPE_BABY, TYPE_BAD, TYPE_FRIEND, TYPE_GAMER, TYPE_NORMAL, TYPE_NORMAL2, TYPE_SANS, TYPE_SILLY, TYPE_ZOOMER]) };
TYPE_TYPE.damage = { none: new Set([TYPE_SANS]), half: new Set([]), double: new Set([]) };
TYPE_UGLY.damage = { none: new Set([TYPE_SANS]), half: new Set([TYPE_BEAN, TYPE_BORING, TYPE_CRAB, TYPE_DARK, TYPE_EMERALD, TYPE_LITTLE, TYPE_PIKACHU, TYPE_SMASH, TYPE_SPACE, TYPE_UGLY]), double: new Set([TYPE_BABY, TYPE_FAIRY, TYPE_GAMER, TYPE_GENDER, TYPE_PSYCHIC, TYPE_VIBE, TYPE_ZOOMER]) };
TYPE_VIBE.damage = { none: new Set([TYPE_GENDER, TYPE_SANS]), half: new Set([TYPE_ANGRY, TYPE_BALL, TYPE_DEEZNUTS, TYPE_EMERALD, TYPE_FAIRY, TYPE_FIGHTING, TYPE_FURRY, TYPE_GUN, TYPE_MAGIC, TYPE_OHIO, TYPE_POISON, TYPE_PSYCHIC, TYPE_SHARP, TYPE_SMASH, TYPE_SONG, TYPE_STINKY, TYPE_SUS, TYPE_VIBE]), double: new Set([TYPE_BABY, TYPE_BAD, TYPE_BUG, TYPE_DANCE, TYPE_DREAM, TYPE_FRIEND, TYPE_GHOST, TYPE_GRASS, TYPE_GUYS, TYPE_NORMAL, TYPE_NORMAL2, TYPE_PRIME, TYPE_SILLY, TYPE_SPACE, TYPE_STEEL, TYPE_WATER, TYPE_ZOOMER]) };
TYPE_WATER.damage = { none: new Set([TYPE_SANS]), half: new Set([TYPE_BEAN, TYPE_CRAB, TYPE_DANCE, TYPE_DRAGON, TYPE_EMERALD, TYPE_GRASS, TYPE_LIQUID, TYPE_PRIME, TYPE_VIBE, TYPE_WATER, TYPE_ZOOMER]), double: new Set([TYPE_BABY, TYPE_BORING, TYPE_FIRE, TYPE_FLUFFY, TYPE_FURRY, TYPE_GAMER, TYPE_GROUND, TYPE_MONKE, TYPE_ROCK, TYPE_SMASH, TYPE_SPACE, TYPE_STINKY, TYPE_UGLY]) };
TYPE_ZOOMER.damage = { none: new Set([]), half: new Set([TYPE_ANGRY, TYPE_BAD, TYPE_DEEZNUTS, TYPE_DREAM, TYPE_EMERALD, TYPE_FAIRY, TYPE_FIGHTING, TYPE_GAMER, TYPE_GRASS, TYPE_GUYS, TYPE_OHIO, TYPE_ROCK, TYPE_SHARP, TYPE_STINKY, TYPE_VIBE]), double: new Set([TYPE_ANCIENT, TYPE_BABY, TYPE_BOOMER, TYPE_BORING, TYPE_BUG, TYPE_FRIEND, TYPE_GUN, TYPE_LEFT, TYPE_LITTLE, TYPE_MAGIC, TYPE_MONKE, TYPE_PRIME, TYPE_RIGHT, TYPE_SANS, TYPE_SUS, TYPE_ZOOMER]) };


export const TYPES: PokemonType[] = [
  TYPE_ANCIENT,TYPE_ANGRY,TYPE_BABY,TYPE_BAD,TYPE_BALL,TYPE_BEAN,TYPE_BOOMER,TYPE_BORING,TYPE_BUG,TYPE_CRAB,TYPE_DANCE,TYPE_DARK,TYPE_DEEZNUTS,TYPE_DRAGON,TYPE_DREAM,TYPE_ELECTRIC,
  TYPE_EMERALD,TYPE_FAIRY,TYPE_FIGHTING,TYPE_FIRE,TYPE_FLUFFY,TYPE_FLYING,TYPE_FRIEND,TYPE_FURRY,TYPE_GAMER,TYPE_GENDER,TYPE_GHOST,TYPE_GRASS,TYPE_GROUND,TYPE_GUN,TYPE_GUYS,TYPE_ICE,
  TYPE_LEFT,TYPE_LIQUID,TYPE_LITTLE,TYPE_MAGIC,TYPE_MONKE,TYPE_NORMAL,TYPE_NORMAL2,TYPE_OHIO,TYPE_OU,TYPE_PIKACHU,TYPE_POISON,TYPE_PRIME,TYPE_PSYCHIC,TYPE_REVERSE,TYPE_RIGHT,TYPE_ROCK,
  TYPE_SANS,TYPE_SHARP,TYPE_SILLY,TYPE_SMASH,TYPE_SONG,TYPE_SPACE,TYPE_STEEL,TYPE_STINKY,TYPE_SUS,TYPE_TYPE,TYPE_UGLY,TYPE_VIBE,TYPE_WATER,TYPE_ZOOMER,
];

/**
 * Types to display when no Attack is selected.
 * Reverse, Type and Deez Nuts have no Attack Move.
 * We might want to hide Emerald as well as it is strong against everything and there is only one attack.
 */
export const TYPES_DEFAULT_ATTACK: PokemonType[] = TYPES.filter(
  (t) => t != TYPE_REVERSE && t != TYPE_TYPE && t != TYPE_DEEZNUTS,
);
